### ISSUE TITLE
FSXA Components miss context for dataset

### ISSUE THREAD

**Issue by ls-espirit** [e-Spirit/fsxa-pattern-library#20]
If a dataset is rendered via fsxa-pattern-lib, other components do not know about this dataset context.

I would suggest expanding the currentPage computed property, so it represents the current dataset context, if any.
Something like this:
```
currentPage: {
  ...
  dataset: {
     entityType: 'item',
     type: 'dataset',
     id: '...',
     identifier: '....', (to fetch dataset from store)
  }
}
```

**Comment by henczi-espirit** [comment]
that sounds reasonable. Would you mind to create an internal Jira ticket and a PR?

**Comment by henczi-espirit** [comment]
Created Ticket for this is TNG-1051 
The feature will be implemented in regular order. If you need this feature to be prioritized, please contact us.

**Comment by JosefBredereck** [comment]
Is this feature already implemented? There is no PR linked, and I can't find TNG-1051 in any PRs either.
