### ISSUE TITLE
Expand fsxa.config capabilities for Components Discovery

### ISSUE THREAD

**Issue by webfussel** [e-Spirit/fsxa-pattern-library#37]
**Description**
Currently we are implementing unit tests in our fsxa-pwa powered nuxt app.
We decided to put the unit tests beside the component into the same folders so components and tests are in the same place every time.

As we also want to test mapping functions used in our `fsxa/sections` templates we would also like to write unit tests for those.

**Problem**
When starting the application after setting up the unit tests the FSXA Library also collects the unit tests and treats them as if they're also components. This leads to errors such as `Reference Error: describe is not defined` as describe is one of the functions used bei `jest` for unit testing.

That happends because as stated in the description of the configuration it will auto collect every file with the extensions `.vue`, `.tsx`, `.jsx` and `.ts` and our unit test files of course are ending with `.ts` in a TypeScript project.

**Proposals**

**Allow file extension filtering**
This proposal is directly taken from the Nuxt config, as they also allow to only collect components when files have specific extensions.
```js
export default {
  components: {
    sections: { path: '~/components/fsxa/sections', extensions: ['vue', 'tsx'] },
  },
}
```

**Allow globs**
This is a standard approach used by many tools such as `webpack`.

```js
export default {
  components: {
    sections: '**/components/fsxa/sections/**/*.(vue|tsx)',
  },
}
```

**Allow ignores with globs or extensions**

```js
export default {
  components: {
    sections: { path: '**/components/fsxa/sections/', ignore: '*.test.*' },
    layouts: { path: '**/components/fsxa/layouts/', ignore: ['ts'] },
  },
}
```

In the best case some mixture of those is implenented, but more freedom would be appreciated.

A quick fix for our project is to just not put unit tests into those directories, but that would break the whole directory structure and would be inconsistent with the rest of the project.

**Comment by henczi-espirit** [comment]
closed original: https://github.com/e-Spirit/fsxa-pwa/issues/62

**Comment by henczi-espirit** [comment]
We fixed the problem of co-located test files being mapped as components, by updating a regex.
Allowing all configurations from the nuxt.config would require to rewrite our component mapper, which should be scheduled separately.

The changes can be viewed here:  https://github.com/e-Spirit/fsxa-nuxt-module/commit/8bd0f9b38086b0ca427bfe732518985dfd9e7b08
